spring:
  application:
    name: movie-service
  profiles:
    active: dev

---
# Profilo di sviluppo
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:moviedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

---
# Profilo di produzione
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate